
'use client';

import { useAdminAuth } from '@/hooks/use-admin-auth';
import { useFirebase, useCollection, useMemoFirebase } from '@/firebase';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { collection, query, orderBy, doc, deleteDoc } from 'firebase/firestore';
import type { CachedRecipe } from '@/lib/types';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import { Trash2, BookOpen, Clock } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useTransition } from 'react';
import { formatDistanceToNow } from 'date-fns';

function CachedRecipeRow({ recipe }: { recipe: CachedRecipe }) {
    const { firestore } = useFirebase();
    const { toast } = useToast();
    const [isDeleting, startDelete] = useTransition();

    const handleDelete = async () => {
        if (!firestore) return;
        startDelete(async () => {
            const recipeRef = doc(firestore, 'cachedRecipes', recipe.id);
            try {
                await deleteDoc(recipeRef);
                toast({ title: "Cache Entry Deleted", description: `The recipe for "${recipe.dishName}" has been cleared.` });
            } catch (err) {
                console.error("Error deleting cached recipe:", err);
                toast({ variant: 'destructive', title: "Deletion Failed", description: "Could not remove the cache entry." });
            }
        });
    };

    const formatDateSafe = (date: any) => {
        if (!date) return 'N/A';
        const jsDate = date.seconds ? new Date(date.seconds * 1000) : new Date(date);
        return `${formatDistanceToNow(jsDate, { addSuffix: true })}`;
    }

    return (
        <TableRow>
            <TableCell className="font-semibold">{recipe.dishName}</TableCell>
            <TableCell>
                <div className="flex flex-wrap gap-1 max-w-md">
                    {recipe.ingredients.map(ing => (
                        <Badge key={ing} variant="secondary">{ing}</Badge>
                    ))}
                </div>
            </TableCell>
            <TableCell className="font-mono text-xs">{formatDateSafe(recipe.createdAt)}</TableCell>
            <TableCell className="text-right">
                <Button variant="ghost" size="icon" onClick={handleDelete} disabled={isDeleting}>
                    <Trash2 className="h-4 w-4" />
                </Button>
            </TableCell>
        </TableRow>
    );
}

export default function CachedRecipesPage() {
    const { isAdmin, isLoading: isAdminLoading } = useAdminAuth();
    const { firestore } = useFirebase();
    const router = useRouter();

    const recipesQuery = useMemoFirebase(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'cachedRecipes'), orderBy('createdAt', 'desc'));
    }, [firestore]);

    const { data: cachedRecipes, isLoading: recipesLoading } = useCollection<CachedRecipe>(recipesQuery);

    if (!isAdminLoading && !isAdmin) {
        router.replace('/dashboard');
        return <p>Redirecting...</p>;
    }

    const isLoading = isAdminLoading || recipesLoading;

    return (
        <div className="container mx-auto py-12 px-4 md:px-6">
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><BookOpen className="h-6 w-6 text-primary" /> Cached Recipe Ingredients</CardTitle>
                    <CardDescription>
                        A list of all recipe ingredients generated by the AI and cached in Firestore to reduce costs.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {isLoading ? (
                         <div className="space-y-4">
                            <Skeleton className="h-12 w-full" />
                            <Skeleton className="h-12 w-full" />
                            <Skeleton className="h-12 w-full" />
                        </div>
                    ) : !cachedRecipes || cachedRecipes.length === 0 ? (
                        <div className="text-center py-12">
                            <Clock className="mx-auto h-12 w-12 text-muted-foreground" />
                             <p className="mt-4 text-lg font-semibold">The cache is empty!</p>
                            <p className="text-muted-foreground mt-2">As users ask for recipes, the results will appear here.</p>
                        </div>
                    ) : (
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Dish Name</TableHead>
                                    <TableHead>Ingredients</TableHead>
                                    <TableHead>Cached On</TableHead>
                                    <TableHead className="text-right">Actions</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {cachedRecipes.map(recipe => (
                                    <CachedRecipeRow key={recipe.id} recipe={recipe} />
                                ))}
                            </TableBody>
                        </Table>
                    )}
                </CardContent>
            </Card>
        </div>
    )
}
