

'use server';

import { revalidatePath } from 'next/cache';
import { promises as fs } from 'fs';
import path from 'path';
import { generalCommands as fileBasedGeneralCommands } from '@/lib/locales/commands';

type CommandGroup = {
  display: string;
  reply: string;
};

type LocaleEntry = string | string[];
type Locales = Record<string, Record<string, LocaleEntry>>;


// --- NEW FILE-BASED DATA FETCHING ---

async function readLocaleFiles(): Promise<Locales> {
    const localesDir = path.join(process.cwd(), 'src', 'lib', 'locales');
    const allLocales: Locales = {};

    try {
        const filenames = await fs.readdir(localesDir);
        for (const filename of filenames) {
            // Skip the main commands file
            if (filename.endsWith('.json') && filename !== 'commands.json') {
                const filePath = path.join(localesDir, filename);
                const fileContent = await fs.readFile(filePath, 'utf-8');
                const jsonContent = JSON.parse(fileContent);
                // The key for the locale is the filename without .json
                const key = filename.replace('.json', '');
                allLocales[key] = jsonContent[key];
            }
        }
    } catch (error) {
        console.error("Error reading locale files:", error);
        return {};
    }
    return allLocales;
}


// --- REFACTORED PUBLIC FUNCTIONS ---

export async function getCommands(): Promise<Record<string, CommandGroup>> {
    // Directly return the imported commands object. No database/file-system call needed here
    // as module imports are cached.
    return Promise.resolve(fileBasedGeneralCommands);
}

export async function getLocales(): Promise<Locales> {
    // This function now reads from the local file system on the server.
    const fileLocales = await readLocaleFiles();
    
    // We also need to add the aliases for the general commands themselves.
    const mergedLocales: Locales = { ...fileLocales };
    for (const key in fileBasedGeneralCommands) {
        mergedLocales[key] = {
            en: [fileBasedGeneralCommands[key].display.toLowerCase()], // Default English alias
        };
    }
    
    return mergedLocales;
}


// --- REFACTORED FILE-BASED SAVING ---

export async function saveCommands(commands: Record<string, CommandGroup>): Promise<{ success: boolean; }> {
    const filePath = path.join(process.cwd(), 'src', 'lib', 'locales', 'commands.ts');
    
    // Construct the file content as a TS module export
    const fileContent = `
// This file is auto-generated by the admin panel. Do not edit manually.
export const generalCommands = ${JSON.stringify(commands, null, 2)};
`.trim();

    try {
        await fs.writeFile(filePath, fileContent, 'utf-8');
        // Revalidate the path to ensure Next.js clears any server-side cache
        revalidatePath('/dashboard/voice-commands');
        return { success: true };
    } catch (error) {
        console.error("Error saving commands to file:", error);
        return { success: false };
    }
}

export async function saveLocales(locales: Locales): Promise<{ success: boolean; }> {
    const localesDir = path.join(process.cwd(), 'src', 'lib', 'locales');

    try {
        for (const key in locales) {
            // Skip general commands, as they are handled by saveCommands
            if (fileBasedGeneralCommands[key]) continue;

            const filename = `${key}.json`;
            const filePath = path.join(localesDir, filename);
            
            const fileContent = JSON.stringify({ [key]: locales[key] }, null, 2);

            try {
                await fs.writeFile(filePath, fileContent, 'utf-8');
            } catch (writeError) {
                 // If a file doesn't exist, it might be a new product/store.
                 // We don't create new files here, just update existing ones.
                 // This function assumes files for all products/stores exist.
                 // A more robust system might create them. For now, log and continue.
                 console.warn(`Could not write to ${filename}, it might be a new item without a corresponding file.`, writeError);
            }
        }
        revalidatePath('/dashboard/voice-commands');
        return { success: true };

    } catch (error) {
        console.error("Error saving locales to files:", error);
        return { success: false };
    }
}


export async function addAliasToLocales(productKey: string, newAlias: string, lang: string): Promise<{ success: boolean }> {
    const aliasLower = newAlias.toLowerCase();
    const filename = `${productKey}.json`;
    const filePath = path.join(process.cwd(), 'src', 'lib', 'locales', filename);

    try {
        let fileContent;
        try {
             fileContent = await fs.readFile(filePath, 'utf-8');
        } catch (e) {
            // File doesn't exist, create it.
            const initialContent = { [productKey]: { [lang]: [aliasLower] } };
            await fs.writeFile(filePath, JSON.stringify(initialContent, null, 2), 'utf-8');
            revalidatePath('/dashboard/voice-commands');
            return { success: true };
        }

        const jsonData = JSON.parse(fileContent);
        if (!jsonData[productKey]) jsonData[productKey] = {};
        if (!jsonData[productKey][lang]) jsonData[productKey][lang] = [];

        const aliases = Array.isArray(jsonData[productKey][lang]) ? jsonData[productKey][lang] : [jsonData[productKey][lang]];
        
        if (!aliases.includes(aliasLower)) {
            aliases.push(aliasLower);
            jsonData[productKey][lang] = aliases;
            await fs.writeFile(filePath, JSON.stringify(jsonData, null, 2), 'utf-8');
        }
        
        revalidatePath('/dashboard/voice-commands');
        return { success: true };

    } catch (error) {
         console.error("Error adding alias to file:", error);
        return { success: false };
    }
}

// This function is not related to locales and can remain as is.
export async function indexSiteContent() {
    try {
        console.log('This function is for demonstration and does not perform a real search index.');
        return {
            success: true,
            message: `Demonstration of site indexing complete.`,
        }

    } catch (error) {
        console.error('Error indexing site content:', error);
        return {
            success: false,
            message: 'Failed to index site content. Check server logs for details.',
        };
    }
}
